:toc:
:toclevels: 3
:toc-title!:
:toc-placement!:
:doctype: book
:chapter-label!:
:data-uri:

= PP-Configuration for Network Device and Stateful Traffic Filter Firewalls

Version: 2.0 draft +
Date: 02-December-2025

*Acknowledgements:*

This PP-Configuration was developed by the Network Device international Technical Community with representatives from industry, Government agencies, Common Criteria Test Laboratories, and members of academia.

*Preface*

=== Related Documents

**Common Criteria**footnote:[For details see http://www.commoncriteriaportal.org/]

[cols="1,3"]
|===
| [CC1]
| Common Criteria for Information Technology Security Evaluation, 
Part 1: Introduction and General Model, 
CCMB-2022-11-001, CC:2022 Revision 1, November 2022.

| [CC2]
| Common Criteria for Information Technology Security Evaluation, 
Part 2: Security Functional Components, 
CCMB-2022-11-002, CC:2022 Revision 1, November 2022.

| [CC3]
| Common Criteria for Information Technology Security Evaluation, 
Part 3: Security Assurance Components, 
CCMB-2022-11-003, CC:2022 Revision 1, November 2022.

| [CC4]
| Common Criteria for Information Technology Security Evaluation, Part 4: Framework for the specification of evaluation methods and activities, CCMB-2022-11-004, CC:2022 Revision 1, November 2022.

| [CC5]
| Common Criteria for Information Technology Security Evaluation, Part 5: Pre-defined packages of security requirements, CCMB-2022-11-005, CC:2022 Revision 1, November 2022.

| [CEM]
| Common Methodology for Information Technology Security Evaluation, CCMB-2022-11-006, CC:2022 Revision 1, November 2022.

| [CC-E&I]
| Errata and Interpretation for CC:2022 (Release 1) and CEM:2022 (Release 1), 002, Version 1.1, July 22, 2024

|===

*Other Documents*

[cols="1,3"]
|===
| [MOD-FW]
| PP-Module for Stateful Traffic Filter Firewalls, Version 2.0 draft, 02 December 2025

| [PP_ND]
| collaborative Protection Profile for Network Devices, Version 4.0, 25 November 2025

| [SD-FW]
| Evaluation Activities for Stateful Traffic Filter Firewalls PP-Configuration, Version 2.0 draft, 02 December 2025

| [SD-ND]
| Evaluation Activities for Network Device cPP, Version 4.0, 25 November 2025
|===

*Revision History*

[cols="1,2,3"]
|===
| *Version*
| *Date*
| *Description*

| 2.0 draft
| 02.12.2025
| CC:2022 version

| 1.4e
| 25.06.2020
| Errata version

| 1.4
| 06.04.2020
| Release version

| 1.3
| 27.09.2019
| Release version

| 1.2
| 19.07.2019
| Updated version

| 1.1
| 05.04.2019
| Minor update

| 1.0
| 08.02.2019
| Initial Draft
|===

*Table of Contents*

toc::[]

:sectnums: all
:sectnumlevels: 4

== Introduction

The scope of this PP-Configuration is to describe the security functionality of a network device, which is in compliance with the PP-Module Base (NDcPP) [PP-ND] that also implements stateful traffic firewall functionality in accordance with the PP-Module for Stateful Traffic Filter Firewalls [MOD-FW].

=== PP-Configuration Reference

This PP-Configuration is identified as follows:
PP-Configuration Reference:  PP-Module for Network Device and Stateful Traffic Filter Firewalls
PP-Configuration Version: 2.0
PP-Configuration Date: 02 December 2025
PP-Configuration shorthand reference: CFG_NDcPP-FW_v2.0

=== PP-Configuration Components statement

This PP-Configuration consists of the following components:

PP-Module Base: collaborative Protection Profile for Network Devices, Version 4.0, 25 November 2025 [PP-ND]  PP-Modules: PP-Module for Stateful Traffic Filter Firewalls, Version 2.0 draft, 02 December 2025 [MOD-FW]



== Conformance Claims


=== CC Conformance - Conformance Statement and Conformance Claims

As defined by the references [CC1], [CC2], [CC3], [CC4], [CC5], [CEM] and [CC-E&I], this PP-Configuration:
conforms to the requirements of Common Criteria CC:2022, Release 1
is Part 2 extended, Part 3 conformant
does not claim conformance to any PP, PP-Module or PP-configuration.
In order to be conformant to this PP-Configuration, an ST must demonstrate Exact Conformance as inherited from the specified PP-Module Base.  This means that all of the SFRs in [PP-ND] section 6 and section 6 of the PP-Module [MOD-FW] must be included in an ST that claims conformance to this PP-Configuration. In addition, SFRs from [PP-ND], Annex A or Annex A of the PP-Module may be included (these are optional SFRs), and SFRs from Annex B of the PP-Module Base must be included according to the selections made, as described in [PP-ND], Annex B.
No PP-Modules are allowed to specify this PP-Configuration as a PP-Module Base.

=== SAR Statement

The Security Assurance Requirements applicable to this PP-Configuration are inherited from the PP-Module Base, i.e. [PP-ND], section 7.

[cols="1,3"]
|===
| *Assurance Class*
| *Assurance Components*

| Security Target (ASE)
| Conformance claims (ASE_CCL.1)

| Security Target (ASE)
| Extended components definition (ASE_ECD.1)

| Security Target (ASE)
| ST introduction (ASE_INT.1)

| Security Target (ASE)
| Security objectives for the operational environment (ASE_OBJ.1)

| Security Target (ASE)
| Stated security requirements (ASE_REQ.1)

| Security Target (ASE)
| Security Problem Definition (ASE_SPD.1)

| Security Target (ASE)
| TOE summary specification (ASE_TSS.1)

| Development (ADV)
| Basic functional specification (ADV_FSP.1)

| Guidance documents (AGD)
| Operational user guidance (AGD_OPE.1)

| Guidance documents (AGD)
| Preparative procedures (AGD_PRE.1)

| Life cycle support (ALC)
| Labelling of the TOE (ALC_CMC.1)

| Life cycle support (ALC)
| TOE CM coverage (ALC_CMS.1)

| Tests (ATE)
| Independent testing – conformance (ATE_IND.1)

| Vulnerability assessment (AVA)
| Vulnerability survey (AVA_VAN.1)

|===

The Supporting Documents provided for the PP_Module Base [SD-ND] and PP-Module [SD-FW] provide specific information with respect to the evaluation of the SARs listed in the table above.